// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReleaseReadinessCoordinator.Data;

#nullable disable

namespace ReleaseReadinessCoordinator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816205343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.BranchResultRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttemptsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Check")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanningDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanningReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReuseSourceResultId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReuseSourceRound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchResults_OperationKey");

                    b.HasIndex("ReuseSourceResultId");

                    b.HasIndex("EvaluationRoundId", "Check")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchResults_Round_Check");

                    b.ToTable("BranchResults", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.CurrentEvidenceRow", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId", "Revision", "Kind");

                    b.HasIndex("EvidenceId")
                        .IsUnique();

                    b.HasIndex("ReleaseId", "Revision", "Kind", "EvidenceId");

                    b.ToTable("CurrentEvidence", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.DecisionSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionBrief")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EarliestValidityBoundUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationRoundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRoundId")
                        .IsUnique();

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_DecisionSnapshots_OperationKey");

                    b.HasIndex("ReleaseId", "Revision");

                    b.ToTable("DecisionSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_DecisionSnapshots_RoundNumber", "RoundNumber > 0");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.DecisionSnapshotSourceRow", b =>
                {
                    b.Property<Guid>("DecisionSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Check")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BranchResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DecisionSnapshotId", "Check");

                    b.HasIndex("BranchResultId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("DecisionSnapshotId", "BranchResultId")
                        .IsUnique();

                    b.ToTable("DecisionSnapshotSources", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.EvaluationRoundRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_EvaluationRounds_OperationKey");

                    b.HasIndex("ReleaseId", "Revision", "RoundNumber")
                        .IsUnique();

                    b.ToTable("EvaluationRounds", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvaluationRounds_Completion", "CompletedAtUtc IS NULL OR CompletedAtUtc >= StartedAtUtc");

                            t.HasCheckConstraint("CK_EvaluationRounds_Number", "RoundNumber > 0");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersedesEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_EvidenceRecords_OperationKey");

                    b.HasIndex("ReleaseId", "Revision", "Kind", "SupersedesEvidenceId");

                    b.HasIndex("ReleaseId", "Revision", "Kind", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_EvidenceRecords_Release_Kind_Version");

                    b.ToTable("EvidenceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvidenceRecords_Version", "Version > 0");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.HumanResponseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeclineReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotConcurrencyToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_HumanResponses_OperationKey");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("SnapshotId");

                    b.HasIndex("ReleaseId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_HumanResponses_Terminal_Release")
                        .HasFilter("ValidationState = 1");

                    b.ToTable("HumanResponses", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PhaseChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedWindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedWindowStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId", "Revision");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ReleaseRevisions_OperationKey");

                    b.ToTable("ReleaseRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReleaseRevisions_DeploymentWindow", "RequestedWindowEndUtc >= RequestedWindowStartUtc");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.RemediationSubmissionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceUpdatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExplicitlySelectedChecksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_RemediationSubmissions_OperationKey");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("RemediationSubmissions", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.TimelineEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_TimelineEntries_OperationKey");

                    b.HasIndex("ReleaseId", "Revision", "Sequence")
                        .IsUnique();

                    b.ToTable("TimelineEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimelineEntries_Sequence", "Sequence > 0");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.WorkflowCorrelationRow", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CorrelatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingRequestKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingWorkflowRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId", "Revision");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowCorrelations_OperationKey");

                    b.HasIndex("PendingWorkflowRequestId")
                        .IsUnique();

                    b.HasIndex("WorkflowSessionId")
                        .IsUnique();

                    b.ToTable("WorkflowCorrelations", (string)null);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.WorkflowRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecisionSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvaluationRoundId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DecisionSnapshotId");

                    b.HasIndex("EvaluationRoundId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowRequests_OperationKey");

                    b.HasIndex("ReleaseId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowRequests_Active_Release")
                        .HasFilter("IsActive = 1");

                    b.ToTable("WorkflowRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowRequests_Closed", "(IsActive = 1 AND ClosedAtUtc IS NULL) OR (IsActive = 0 AND ClosedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.BranchResultRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.EvaluationRoundRow", null)
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReleaseReadinessCoordinator.Data.BranchResultRow", null)
                        .WithMany()
                        .HasForeignKey("ReuseSourceResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.CurrentEvidenceRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision", "Kind", "EvidenceId")
                        .HasPrincipalKey("ReleaseId", "Revision", "Kind", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.DecisionSnapshotRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.EvaluationRoundRow", null)
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.DecisionSnapshotSourceRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.BranchResultRow", null)
                        .WithMany()
                        .HasForeignKey("BranchResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.DecisionSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("DecisionSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.EvaluationRoundRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.EvidenceRecordRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision", "Kind", "SupersedesEvidenceId")
                        .HasPrincipalKey("ReleaseId", "Revision", "Kind", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.HumanResponseRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.WorkflowRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.DecisionSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.RemediationSubmissionRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.WorkflowRequestRow", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.TimelineEntryRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.WorkflowCorrelationRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseReadinessCoordinator.Data.WorkflowRequestRow", b =>
                {
                    b.HasOne("ReleaseReadinessCoordinator.Data.DecisionSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("DecisionSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReleaseReadinessCoordinator.Data.EvaluationRoundRow", null)
                        .WithMany()
                        .HasForeignKey("EvaluationRoundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReleaseReadinessCoordinator.Data.ReleaseRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
